### ISSUE TITLE
Submission system: add asterisk (*) to required webform fields

### ISSUE THREAD

**Issue by drodz11** [fsulib/fsu_strata#4]
Link to dev site: http://dev.submit.diginole.lib.fsu.edu/

Link to "progenitor"/uber webform: http://dev.submit.diginole.lib.fsu.edu/diginole-submission-form

Issue: Normally in Drupal webforms, elements that are required have an asterisk (*) next to the field label. These asterisks are not showing up in the submission system, despite webform elements being selected as "required" from the build page.

Desired outcome: Asterisks displaying correctly next to required webform element labels on all webforms and variants.

Possible solution: According to Brian A., adding the following CSS to the asset injector in LDBase fixed a similar issue in that system:

`.form-required:after {
display: inline-block;
width: 6px;
height: 6px;
margin: 0 0.3em;
content: "";
vertical-align: super;
background-image: url(../../../../misc/icons/ee0000/required.svg);
background-repeat: no-repeat;
background-size: 6px 6px;
}`

Simply adding this code to the asset injector of the submission system VM did not produce the desired results, but perhaps updating the file-path for the `background-image` attribute or adding the appropriate `svg` at the designated location would resolve the issue.

**Comment by Favenzio** [comment]
Implemented fix. Issue closed.
